using System.Diagnostics.CodeAnalysis;

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

using Npgsql;

using WattWise.Infrastructure.Persistence;
using WattWise.Infrastructure.Persistence.Schema;

namespace WattWise.Infrastructure.IntegrationTests;

[SuppressMessage("Security", "EF1003:Possible SQL injection", Justification = "Schema names can't be parameters; only DatabaseSchemas constants are concatenated, values are parameters.")]
public class RoleAccessTests(DatabaseFixture fixture) : IClassFixture<DatabaseFixture>, IAsyncLifetime
{
    private const string PermissionDenied = "42501";
    private static readonly string[] ProbeSchemas = [DatabaseSchemas.App, DatabaseSchemas.Hangfire, DatabaseSchemas.Migrations];

    // Tests in a class run one after another, so the probe tables are created idempotently for each and never raced.
    public async ValueTask InitializeAsync()
    {
        await using ServiceProvider provider = fixture.BuildServices(DatabaseRole.Cli);
        await using AsyncServiceScope scope = provider.CreateAsyncScope();
        AppDbContext db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

        foreach (string schema in ProbeSchemas)
        {
            await db.Database.ExecuteSqlRawAsync(
                "CREATE TABLE IF NOT EXISTS " + Table(schema) + " (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, note text)",
                Token);
        }
    }

    public ValueTask DisposeAsync() => ValueTask.CompletedTask;

    [Theory]
    [InlineData(DatabaseRole.Api, DatabaseSchemas.App)]
    [InlineData(DatabaseRole.Jobs, DatabaseSchemas.App)]
    [InlineData(DatabaseRole.Jobs, DatabaseSchemas.Hangfire)]
    public async Task Role_reads_and_writes_its_schema(DatabaseRole role, string schema)
    {
        await using ServiceProvider provider = fixture.BuildServices(role);
        await using AsyncServiceScope scope = provider.CreateAsyncScope();
        AppDbContext db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

        List<int> ids = await db.Database
            .SqlQueryRaw<int>("INSERT INTO " + Table(schema) + " (note) VALUES ({0}) RETURNING id AS \"Value\"", "inserted")
            .ToListAsync(Token);
        int id = Assert.Single(ids);
        string selected = await db.Database
            .SqlQueryRaw<string>("SELECT note AS \"Value\" FROM " + Table(schema) + " WHERE id = {0}", id)
            .SingleAsync(Token);
        int updated = await db.Database.ExecuteSqlRawAsync("UPDATE " + Table(schema) + " SET note = {0} WHERE id = {1}", ["updated", id], Token);
        int deleted = await db.Database.ExecuteSqlRawAsync("DELETE FROM " + Table(schema) + " WHERE id = {0}", [id], Token);

        Assert.Equal("inserted", selected);
        Assert.Equal(1, updated);
        Assert.Equal(1, deleted);
    }

    [Theory]
    [InlineData(DatabaseRole.Api, DatabaseSchemas.Hangfire)]
    [InlineData(DatabaseRole.Api, DatabaseSchemas.Migrations)]
    [InlineData(DatabaseRole.Jobs, DatabaseSchemas.Migrations)]
    public async Task Role_cannot_read_another_schema(DatabaseRole role, string schema)
    {
        await using ServiceProvider provider = fixture.BuildServices(role);
        await using AsyncServiceScope scope = provider.CreateAsyncScope();
        AppDbContext db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

        PostgresException exception = await Assert.ThrowsAsync<PostgresException>(
            () => db.Database.SqlQueryRaw<long>("SELECT count(*) AS \"Value\" FROM " + Table(schema)).ToListAsync(Token));

        Assert.Equal(PermissionDenied, exception.SqlState);
    }

    [Theory]
    [InlineData(DatabaseRole.Api, DatabaseSchemas.App)]
    [InlineData(DatabaseRole.Api, DatabaseSchemas.Hangfire)]
    [InlineData(DatabaseRole.Api, DatabaseSchemas.Migrations)]
    [InlineData(DatabaseRole.Jobs, DatabaseSchemas.App)]
    [InlineData(DatabaseRole.Jobs, DatabaseSchemas.Hangfire)]
    [InlineData(DatabaseRole.Jobs, DatabaseSchemas.Migrations)]
    public async Task Role_cannot_create_tables(DatabaseRole role, string schema)
    {
        await using ServiceProvider provider = fixture.BuildServices(role);
        await using AsyncServiceScope scope = provider.CreateAsyncScope();
        AppDbContext db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

        PostgresException exception = await Assert.ThrowsAsync<PostgresException>(
            () => db.Database.ExecuteSqlRawAsync("CREATE TABLE " + schema + ".ddl_probe (id int)", Token));

        Assert.Equal(PermissionDenied, exception.SqlState);
    }

    [Fact]
    public async Task Migration_history_lives_in_its_own_schema_owned_by_owner()
    {
        await using ServiceProvider provider = fixture.BuildServices(DatabaseRole.Cli);
        await using AsyncServiceScope scope = provider.CreateAsyncScope();
        AppDbContext db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

        string? schema = await db.Database
            .SqlQuery<string>($"SELECT schemaname AS \"Value\" FROM pg_tables WHERE tablename = '__ef_migrations_history'")
            .SingleOrDefaultAsync(Token);
        string? owner = await db.Database
            .SqlQuery<string>($"SELECT tableowner AS \"Value\" FROM pg_tables WHERE tablename = '__ef_migrations_history'")
            .SingleOrDefaultAsync(Token);

        Assert.Equal(DatabaseSchemas.Migrations, schema);
        Assert.Equal("owner", owner);
    }

    private static CancellationToken Token => TestContext.Current.CancellationToken;

    private static string Table(string schema) => schema + ".access_probe";
}
