<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="IfDifferent" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="WattWise.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WattWise.Testing\WattWise.Testing.csproj" />
    <ProjectReference Include="..\..\src\WattWise.Api\WattWise.Api.csproj" />
  </ItemGroup>

</Project>
